name:          Guía de Código por @mdo
description:   Estándares para desarrollar HTML y CSS, flexibles, duraderos y sustentables.
url:           http://adrianayala.mx/code-guide/es

markdown:      rdiscount
permalink:     pretty
pygments:      true
