name:          Guía de Código por @mdo
description:   Estándares para desarrollar HTML y CSS, flexibles, duraderos y sustentables.
url:           http://mdo.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
